# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-16 20:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actions', '0029_auto_20170307_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='CongressTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(blank=True, max_length=5000, null=True)),
                ('scipts_use_position_data', models.BooleanField(default=False)),
                ('action', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='actions.Action')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneScript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('default', models.BooleanField(default=False)),
                ('always', models.BooleanField(default=False)),
                ('always_reps', models.CharField(blank=True, max_length=300)),
                ('priority', models.CharField(choices=[('high', 'High Priority'), ('medium', 'Medium Priority'), ('low', 'Low Priority')], default='medium', max_length=6)),
                ('rep_type', models.CharField(choices=[('senator', 'Senator'), ('rep', 'Representative'), ('both', 'Both')], default='both', max_length=7)),
                ('party', models.CharField(choices=[('democrat', 'Democrat'), ('republican', 'Republican'), ('all', 'All')], default='all', max_length=10)),
                ('position', models.CharField(choices=[('for', 'For'), ('against', 'Against'), ('undecided', 'Undecided'), ('unknown', 'Position unknown')], default='unknown', max_length=9)),
                ('committees', models.CharField(blank=True, max_length=30)),
                ('states', models.CharField(blank=True, max_length=200)),
                ('districts', models.CharField(blank=True, max_length=300)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actions.Action')),
            ],
        ),
    ]
