# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-22 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonescript_plugin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonescript',
            name='always',
        ),
        migrations.RemoveField(
            model_name='phonescript',
            name='default',
        ),
        migrations.AddField(
            model_name='phonescript',
            name='script_type',
            field=models.CharField(choices=[('default', 'Default'), ('constituent', 'Constituent'), ('universal', 'Universal')], default='none', max_length=11),
        ),
    ]
