# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-03 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonescript_plugin', '0002_auto_20170322_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congresstracker',
            name='data',
            field=models.CharField(blank=True, max_length=25000, null=True),
        ),
        migrations.AlterField(
            model_name='phonescript',
            name='position',
            field=models.CharField(choices=[('for', 'For'), ('against', 'Against'), ('undecided', 'Undecided'), ('unknown', 'Position unknown'), ('all', 'All')], default='unknown', max_length=9),
        ),
        migrations.AlterField(
            model_name='phonescript',
            name='priority',
            field=models.CharField(choices=[('3', 'High Priority'), ('2', 'Medium Priority'), ('1', 'Low Priority')], default='2', max_length=6),
        ),
    ]
