# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-03 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonescript_plugin', '0003_auto_20170403_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congresstracker',
            name='data',
            field=models.CharField(blank=True, max_length=75000, null=True),
        ),
    ]
