# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-03 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0029_auto_20170307_2026'),
        ('phonescript_plugin', '0004_auto_20170403_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Legislator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bioguide_id', models.CharField(max_length=9)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=11)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('district', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScriptMatcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('for', 'For'), ('against', 'Against'), ('undecided', 'Undecided'), ('unknown', 'Position unknown'), ('all', 'All')], default='unknown', max_length=9)),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actions.Action')),
                ('legislator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phonescript_plugin.Legislator')),
                ('script', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='phonescript_plugin.PhoneScript')),
            ],
        ),
        migrations.RemoveField(
            model_name='congresstracker',
            name='action',
        ),
        migrations.DeleteModel(
            name='CongressTracker',
        ),
    ]
