# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-03 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonescript_plugin', '0005_auto_20170403_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legislator',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
