# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-03 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonescript_plugin', '0006_auto_20170403_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonescript',
            name='rep_type',
            field=models.CharField(choices=[('sen', 'Senator'), ('rep', 'Representative'), ('both', 'Both')], default='both', max_length=7),
        ),
    ]
