# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-03 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonescript_plugin', '0007_auto_20170403_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='legislator',
            name='party',
            field=models.CharField(default='d', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='phonescript',
            name='party',
            field=models.CharField(choices=[('d', 'Democrat'), ('r', 'Republican'), ('all', 'All')], default='all', max_length=10),
        ),
    ]
