# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-20 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonescript_plugin', '0008_auto_20170403_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonescript',
            name='position',
            field=models.CharField(choices=[('for', 'For'), ('against', 'Against'), ('undecided', 'Undecided'), ('unknown', 'Position unknown'), ('all', 'All')], default='all', max_length=9),
        ),
        migrations.AlterField(
            model_name='phonescript',
            name='script_type',
            field=models.CharField(choices=[('default', 'Default'), ('constituent', 'constituent'), ('univeral', 'Universal')], default='default', max_length=11),
        ),
    ]
