# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-23 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonescript_plugin', '0009_auto_20170420_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='legislator',
            name='in_office',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='phonescript',
            name='script_type',
            field=models.CharField(choices=[('default', 'Default'), ('constituent', 'Constituent'), ('universal', 'Universal')], default='default', max_length=11),
        ),
    ]
