# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-16 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonescript_plugin', '0010_auto_20170423_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonescript',
            name='party',
            field=models.CharField(choices=[('D', 'Democrat'), ('R', 'Republican'), ('all', 'All')], default='all', max_length=10),
        ),
    ]
