# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0002_flag_flag_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flag',
            name='flag_status',
            field=models.CharField(choices=[('new', 'New flag'), ('reject', 'Flag was rejected as invalid'), ('approve', 'Flag was approved as valid'), ('discuss', 'Flag needs further investigation')], default='new', max_length=10),
        ),
    ]
