# Alternatively, we could query for this each time, but it seems like a waste.  But possibly
# once we implement caching, we can get rid of this and just do a query.

states = [u'---', u'AK', u'AL', u'AR', u'AS', u'AZ', u'CA', u'CO', u'CT', u'DC', u'DE',
    u'FL', u'GA', u'GU', u'HI', u'IA', u'ID', u'IL', u'IN', u'KS', u'KY', u'LA',
    u'MA', u'MD', u'ME', u'MI', u'MN', u'MO', u'MP', u'MS', u'MT', u'NC', u'ND',
    u'NE', u'NH', u'NJ', u'NM', u'NV', u'NY', u'OH', u'OK', u'OR', u'PA', u'PR',
    u'RI', u'SC', u'SD', u'TN', u'TX', u'UT', u'VA', u'VI', u'VT', u'WA', u'WI',
    u'WV', u'WY']

districts = [u'---', u'AK-0 (Young)', u'AL-1 (Byrne)', u'AL-2 (Roby)', u'AL-3 (Rogers)',
    u'AL-4 (Aderholt)', u'AL-5 (Brooks)', u'AL-6 (Palmer)', u'AL-7 (Sewell)', u'AR-1 (Crawford)',
    u'AR-2 (Hill)', u'AR-3 (Womack)', u'AR-4 (Westerman)', u'AS-0 (Amata)', u"AZ-1 (O'Halleran)",
    u'AZ-2 (McSally)', u'AZ-3 (Grijalva)', u'AZ-4 (Gosar)', u'AZ-5 (Biggs)', u'AZ-6 (Schweikert)',
    u'AZ-7 (Gallego)', u'AZ-8 (Franks)', u'AZ-9 (Sinema)', u'CA-1 (LaMalfa)',
    u'CA-2 (Huffman)', u'CA-3 (Garamendi)', u'CA-4 (McClintock)', u'CA-5 (Thompson)',
    u'CA-6 (Matsui)', u'CA-7 (Bera)', u'CA-8 (Cook)', u'CA-9 (McNerney)', u'CA-10 (Denham)',
    u'CA-11 (DeSaulnier)', u'CA-12 (Pelosi)', u'CA-13 (Lee)', u'CA-14 (Speier)',
    u'CA-15 (Swalwell)', u'CA-16 (Costa)', u'CA-17 (Khanna)', u'CA-18 (Eshoo)',
    u'CA-19 (Lofgren)', u'CA-20 (Panetta)', u'CA-21 (Valadao)', u'CA-22 (Nunes)',
    u'CA-23 (McCarthy)', u'CA-24 (Carbajal)', u'CA-25 (Knight)', u'CA-26 (Brownley)',
    u'CA-27 (Chu)', u'CA-28 (Schiff)', u'CA-29 (C\xe1rdenas)', u'CA-30 (Sherman)',
    u'CA-31 (Aguilar)', u'CA-32 (Napolitano)', u'CA-33 (Lieu)', u'CA-35 (Torres)',
    u'CA-36 (Ruiz)', u'CA-37 (Bass)', u'CA-38 (S\xe1nchez)', u'CA-39 (Royce)',
    u'CA-40 (Roybal-Allard)', u'CA-41 (Takano)', u'CA-42 (Calvert)', u'CA-43 (Waters)',
    u'CA-44 (Barrag\xe1n)', u'CA-45 (Walters)', u'CA-46 (Correa)', u'CA-47 (Lowenthal)',
    u'CA-48 (Rohrabacher)', u'CA-49 (Issa)', u'CA-50 (Hunter)', u'CA-51 (Vargas)',
    u'CA-52 (Peters)', u'CA-53 (Davis)',
    u'CO-1 (DeGette)', u'CO-2 (Polis)', u'CO-3 (Tipton)', u'CO-4 (Buck)', u'CO-5 (Lamborn)',
    u'CO-6 (Coffman)', u'CO-7 (Perlmutter)', u'CT-1 (Larson)', u'CT-2 (Courtney)',
    u'CT-3 (DeLauro)', u'CT-4 (Himes)', u'CT-5 (Esty)', u'DC-0 (Norton)', u'DE-0 (Blunt Rochester)',
    u'FL-1 (Gaetz)', u'FL-2 (Dunn)', u'FL-3 (Yoho)', u'FL-4 (Rutherford)', u'FL-5 (Lawson)',
    u'FL-6 (DeSantis)', u'FL-7 (Murphy)', u'FL-8 (Posey)', u'FL-9 (Soto)',
    u'FL-10 (Demings)', u'FL-11 (Webster)', u'FL-12 (Bilirakis)', u'FL-13 (Crist)',
    u'FL-14 (Castor)', u'FL-15 (Ross)', u'FL-16 (Buchanan)', u'FL-17 (Rooney)',
    u'FL-18 (Mast)', u'FL-19 (Rooney)', u'FL-20 (Hastings)', u'FL-21 (Frankel)',
    u'FL-22 (Deutch)', u'FL-23 (Wasserman Schultz)', u'FL-24 (Wilson)', u'FL-25 (Diaz-Balart)',
    u'FL-26 (Curbelo)', u'FL-27 (Ros-Lehtinen)', u'GA-1 (Carter)',
    u'GA-2 (Bishop)', u'GA-3 (Ferguson)', u'GA-4 (Johnson)', u'GA-5 (Lewis)',
    u'GA-7 (Woodall)', u'GA-8 (Scott)', u'GA-9 (Collins)', u'GA-10 (Hice)',
    u'GA-11 (Loudermilk)', u'GA-12 (Allen)', u'GA-13 (Scott)', u'GA-14 (Graves)', u'GU-0 (Bordallo)',
    u'HI-1 (Hanabusa)', u'HI-2 (Gabbard)', u'IA-1 (Blum)', u'IA-2 (Loebsack)',
    u'IA-3 (Young)', u'IA-4 (King)', u'ID-1 (Labrador)', u'ID-2 (Simpson)',
    u'IL-1 (Rush)', u'IL-2 (Kelly)', u'IL-3 (Lipinski)', u'IL-4 (Guti\xe9rrez)',
    u'IL-5 (Quigley)', u'IL-6 (Roskam)', u'IL-7 (Davis)', u'IL-8 (Krishnamoorthi)',
    u'IL-9 (Schakowsky)', u'IL-10 (Schneider)', u'IL-11 (Foster)', u'IL-12 (Bost)',
    u'IL-13 (Davis)', u'IL-14 (Hultgren)', u'IL-15 (Shimkus)', u'IL-16 (Kinzinger)',
    u'IL-17 (Bustos)', u'IL-18 (LaHood)',  u'IN-1 (Visclosky)',
    u'IN-2 (Walorski)', u'IN-3 (Banks)', u'IN-4 (Rokita)', u'IN-5 (Brooks)',
    u'IN-6 (Messer)', u'IN-7 (Carson)', u'IN-8 (Bucshon)', u'IN-9 (Hollingsworth)',
    u'KS-1 (Marshall)', u'KS-2 (Jenkins)', u'KS-3 (Yoder)', u'KY-1 (Comer)',
    u'KY-2 (Guthrie)', u'KY-3 (Yarmuth)', u'KY-4 (Massie)', u'KY-5 (Rogers)',
    u'KY-6 (Barr)', u'LA-1 (Scalise)', u'LA-2 (Richmond)', u'LA-3 (Higgins)',
    u'LA-4 (Johnson)', u'LA-5 (Abraham)', u'LA-6 (Graves)', u'MA-1 (Neal)',
    u'MA-2 (McGovern)', u'MA-3 (Tsongas)', u'MA-4 (Kennedy)', u'MA-5 (Clark)',
    u'MA-6 (Moulton)', u'MA-7 (Capuano)', u'MA-8 (Lynch)', u'MA-9 (Keating)',
    u'MD-1 (Harris)', u'MD-2 (Ruppersberger)', u'MD-3 (Sarbanes)', u'MD-4 (Brown)',
    u'MD-5 (Hoyer)', u'MD-6 (Delaney)', u'MD-7 (Cummings)', u'MD-8 (Raskin)',
    u'ME-1 (Pingree)', u'ME-2 (Poliquin)', u'MI-1 (Bergman)', u'MI-2 (Huizenga)',
    u'MI-3 (Amash)', u'MI-4 (Moolenaar)', u'MI-5 (Kildee)', u'MI-6 (Upton)',
    u'MI-7 (Walberg)', u'MI-8 (Bishop)', u'MI-9 (Levin)', u'MI-10 (Mitchell)',
    u'MI-11 (Trott)', u'MI-12 (Dingell)', u'MI-13 (Conyers)', u'MI-14 (Lawrence)',
    u'MN-1 (Walz)', u'MN-2 (Lewis)', u'MN-3 (Paulsen)', u'MN-4 (McCollum)', u'MN-5 (Ellison)',
    u'MN-6 (Emmer)', u'MN-7 (Peterson)', u'MN-8 (Nolan)', u'MO-1 (Clay)', u'MO-2 (Wagner)',
    u'MO-3 (Luetkemeyer)', u'MO-4 (Hartzler)', u'MO-5 (Cleaver)', u'MO-6 (Graves)',
    u'MO-7 (Long)', u'MO-8 (Smith)', u'MP-0 (Sablan)', u'MS-1 (Kelly)', u'MS-2 (Thompson)',
    u'MS-3 (Harper)', u'MS-4 (Palazzo)', u'NC-1 (Butterfield)',  u'NC-2 (Holding)',
    u'NC-3 (Jones)', u'NC-4 (Price)', u'NC-5 (Foxx)', u'NC-6 (Walker)', u'NC-7 (Rouzer)',
    u'NC-8 (Hudson)', u'NC-9 (Pittenger)', u'NC-10 (McHenry)', u'NC-11 (Meadows)',
    u'NC-12 (Adams)', u'NC-13 (Budd)', u'ND-0 (Cramer)', u'NE-1 (Fortenberry)', u'NE-2 (Bacon)',
    u'NE-3 (Smith)', u'NH-1 (Shea-Porter)', u'NH-2 (Kuster)', u'NJ-1 (Norcross)',
    u'NJ-2 (LoBiondo)', u'NJ-3 (MacArthur)', u'NJ-4 (Smith)', u'NJ-5 (Gottheimer)',
    u'NJ-6 (Pallone)', u'NJ-7 (Lance)', u'NJ-8 (Sires)', u'NJ-9 (Pascrell)',
    u'NJ-10 (Payne)', u'NJ-11 (Frelinghuysen)', u'NJ-12 (Watson Coleman)', u'NM-1 (Lujan Grisham)',
    u'NM-2 (Pearce)', u'NM-3 (Luj\xe1n)', u'NV-1 (Titus)', u'NV-2 (Amodei)',
    u'NV-3 (Rosen)', u'NV-4 (Kihuen)', u'NY-1 (Zeldin)', u'NY-2 (King)', u'NY-3 (Suozzi)',
    u'NY-4 (Rice)', u'NY-5 (Meeks)', u'NY-6 (Meng)', u'NY-7 (Vel\xe1zquez)', u'NY-8 (Jeffries)',
    u'NY-9 (Clarke)', u'NY-10 (Nadler)', u'NY-11 (Donovan)', u'NY-12 (Maloney)',
    u'NY-13 (Espaillat)', u'NY-14 (Crowley)', u'NY-15 (Serrano)', u'NY-16 (Engel)',
    u'NY-17 (Lowey)', u'NY-18 (Maloney)', u'NY-19 (Faso)', u'NY-20 (Tonko)', u'NY-21 (Stefanik)',
    u'NY-22 (Tenney)', u'NY-23 (Reed)', u'NY-24 (Katko)', u'NY-25 (Slaughter)',
    u'NY-26 (Higgins)', u'NY-27 (Collins)', u'OH-1 (Chabot)', u'OH-2 (Wenstrup)',
    u'OH-3 (Beatty)', u'OH-4 (Jordan)', u'OH-5 (Latta)', u'OH-6 (Johnson)', u'OH-7 (Gibbs)',
    u'OH-8 (Davidson)', u'OH-9 (Kaptur)', u'OH-10 (Turner)', u'OH-11 (Fudge)', u'OH-12 (Tiberi)',
    u'OH-13 (Ryan)', u'OH-14 (Joyce)', u'OH-15 (Stivers)', u'OH-16 (Renacci)',
    u'OK-1 (Bridenstine)', u'OK-2 (Mullin)', u'OK-3 (Lucas)', u'OK-4 (Cole)', u'OK-5 (Russell)',
    u'OR-1 (Bonamici)', u'OR-2 (Walden)', u'OR-3 (Blumenauer)', u'OR-4 (DeFazio)',
    u'OR-5 (Schrader)', u'PA-1 (Brady)', u'PA-2 (Evans)', u'PA-3 (Kelly)', u'PA-4 (Perry)',
    u'PA-5 (Thompson)', u'PA-6 (Costello)', u'PA-7 (Meehan)', u'PA-8 (Fitzpatrick)',
    u'PA-9 (Shuster)', u'PA-10 (Marino)', u'PA-11 (Barletta)', u'PA-12 (Rothfus)',
    u'PA-13 (Boyle)', u'PA-14 (Doyle)', u'PA-15 (Dent)', u'PA-16 (Smucker)', u'PA-17 (Cartwright)',
    u'PA-18 (Murphy)', u'PR-0 (Gonz\xe1lez-Col\xf3n)', u'RI-1 (Cicilline)', u'RI-2 (Langevin)',
    u'SC-1 (Sanford)', u'SC-2 (Wilson)', u'SC-3 (Duncan)', u'SC-4 (Gowdy)', u'SC-6 (Clyburn)',
    u'SC-7 (Rice)', u'SD-0 (Noem)', u'TN-1 (Roe)', u'TN-2 (Duncan)', u'TN-3 (Fleischmann)',
    u'TN-4 (DesJarlais)', u'TN-5 (Cooper)', u'TN-6 (Black)', u'TN-7 (Blackburn)',
    u'TN-8 (Kustoff)', u'TN-9 (Cohen)', u'TX-1 (Gohmert)', u'TX-2 (Poe)', u'TX-3 (Johnson)',
    u'TX-4 (Ratcliffe)', u'TX-5 (Hensarling)', u'TX-6 (Barton)', u'TX-7 (Culberson)',
    u'TX-8 (Brady)', u'TX-9 (Green)', u'TX-10 (McCaul)', u'TX-11 (Conaway)', u'TX-12 (Granger)',
    u'TX-13 (Thornberry)', u'TX-14 (Weber)', u'TX-15 (Gonzalez)', u"TX-16 (O'Rourke)",
    u'TX-17 (Flores)', u'TX-18 (Jackson Lee)', u'TX-19 (Arrington)', u'TX-20 (Castro)',
    u'TX-21 (Smith)', u'TX-22 (Olson)', u'TX-23 (Hurd)', u'TX-24 (Marchant)',
    u'TX-25 (Williams)', u'TX-26 (Burgess)', u'TX-27 (Farenthold)', u'TX-28 (Cuellar)',
    u'TX-29 (Green)', u'TX-30 (Johnson)', u'TX-31 (Carter)', u'TX-32 (Sessions)',
    u'TX-33 (Veasey)', u'TX-34 (Vela)', u'TX-35 (Doggett)', u'TX-36 (Babin)',  u'UT-1 (Bishop)',
    u'UT-2 (Stewart)', u'UT-3 (Chaffetz)', u'UT-4 (Love)', u'VA-1 (Wittman)',
    u'VA-2 (Taylor)', u'VA-3 (Scott)', u'VA-4 (McEachin)', u'VA-5 (Garrett)',
    u'VA-6 (Goodlatte)', u'VA-7 (Brat)', u'VA-8 (Beyer)', u'VA-9 (Griffith)',
    u'VA-10 (Comstock)', u'VA-11 (Connolly)', u'VI-0 (Plaskett)', u'VT-0 (Welch)',
    u'WA-1 (DelBene)', u'WA-2 (Larsen)', u'WA-3 (Herrera Beutler)', u'WA-4 (Newhouse)',
    u'WA-5 (McMorris Rodgers)', u'WA-6 (Kilmer)', u'WA-7 (Jayapal)', u'WA-8 (Reichert)',
    u'WA-9 (Smith)', u'WA-10 (Heck)', u'WI-1 (Ryan)', u'WI-2 (Pocan)', u'WI-3 (Kind)',
    u'WI-4 (Moore)', u'WI-5 (Sensenbrenner)', u'WI-6 (Grothman)', u'WI-7 (Duffy)',
    u'WI-8 (Gallagher)', u'WV-1 (McKinley)', u'WV-2 (Mooney)', u'WV-3 (Jenkins)',
    u'WY-0 (Cheney)']
