# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
