# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='person_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_people', to='profiles.Profile'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='person_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_people', to='profiles.Profile'),
        ),
    ]
