# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20161113_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relationship',
            old_name='mute',
            new_name='A_accountable_B',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='person_from',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='person_to',
        ),
        migrations.AddField(
            model_name='relationship',
            name='A_follows_B',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relationship',
            name='A_mutes_B',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relationship',
            name='B_accountable_A',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relationship',
            name='B_follows_A',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relationship',
            name='B_mutes_A',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relationship',
            name='person_A',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='relationship_A', to='profiles.Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relationship',
            name='person_B',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='relationship_B', to='profiles.Profile'),
            preserve_default=False,
        ),
    ]
