# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0004_auto_20161115_1705'),
        ('profiles', '0005_auto_20161114_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileActionRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[(b'low', b'Low'), (b'med', b'Medium'), (b'hig', b'High'), (b'eme', b'Emergency')], default='med', max_length=3)),
                ('privacy', models.CharField(choices=[(b'pub', b'Visible to Public'), (b'sit', b'Visible Sitewide'), (b'fol', b'Visible to Buddies and Those You Follow'), (b'bud', b'Visible to Buddies'), (b'you', b'Only Visible to You'), (b'inh', b'Inherit')], default='inh', max_length=3)),
                ('status', models.CharField(choices=[(b'sug', b'Suggested to you'), (b'com', b'Committed to doing'), (b'don', b'Done'), (b'wit', b'Rejected')], default='inh', max_length=3)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actions.Action')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
            ],
        ),
        migrations.AlterField(
            model_name='privacydefaults',
            name='global_default',
            field=models.CharField(choices=[(b'pub', b'Visible to Public'), (b'sit', b'Visible Sitewide'), (b'fol', b'Visible to Buddies and Those You Follow'), (b'bud', b'Visible to Buddies'), (b'you', b'Only Visible to You'), (b'inh', b'Inherit')], default='fol', max_length=3),
        ),
    ]
