# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0004_auto_20161115_1705'),
        ('profiles', '0006_auto_20161115_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='actions',
            field=models.ManyToManyField(through='profiles.ProfileActionRelationship', to='actions.Action'),
        ),
        migrations.AddField(
            model_name='profileactionrelationship',
            name='committed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profileactionrelationship',
            name='status',
            field=models.CharField(choices=[(b'sug', b'Suggested to you'), (b'ace', b'Accepted'), (b'don', b'Done'), (b'wit', b'Rejected')], default='inh', max_length=3),
        ),
    ]
