# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 00:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20161115_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacydefaults',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_defaults', to=settings.AUTH_USER_MODEL),
        ),
    ]
