# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 00:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20161116_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privacydefaults',
            name='user',
        ),
        migrations.AddField(
            model_name='privacydefaults',
            name='profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='privacy_defaults', to='profiles.Profile'),
            preserve_default=False,
        ),
    ]
