# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20161116_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='privacy',
            field=models.CharField(choices=[(b'pub', b'Visible to Public'), (b'sit', b'Visible Sitewide'), (b'fol', b'Visible to Buddies and Those You Follow'), (b'bud', b'Visible to Buddies'), (b'you', b'Only Visible to You'), (b'inh', b'Inherit')], default='inh', max_length=3),
        ),
    ]
