# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_profile_privacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacydefaults',
            name='global_default',
            field=models.CharField(choices=[(b'pub', b'Visible to Public'), (b'sit', b'Visible Sitewide')], default='fol', max_length=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='privacy',
            field=models.CharField(choices=[(b'pub', b'Visible to Public'), (b'sit', b'Visible Sitewide'), (b'inh', b'Inherit')], default='inh', max_length=3),
        ),
        migrations.AlterField(
            model_name='profileactionrelationship',
            name='privacy',
            field=models.CharField(choices=[(b'pub', b'Visible to Public'), (b'sit', b'Visible Sitewide'), (b'inh', b'Inherit')], default='inh', max_length=3),
        ),
    ]
