# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20161116_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacydefaults',
            name='global_default',
            field=models.CharField(choices=[(b'pub', b'Visible to Public'), (b'sit', b'Visible Sitewide')], default='sit', max_length=3),
        ),
    ]
