# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20161117_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileactionrelationship',
            name='status',
            field=models.CharField(choices=[(b'sug', b'Suggested to you'), (b'ace', b'Accepted'), (b'don', b'Done'), (b'wit', b'Rejected')], default='ace', max_length=3),
        ),
    ]
