# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 02:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auto_20161117_0404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='text',
            new_name='description',
        ),
    ]
