# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_profile_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
    ]
