# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_auto_20161126_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileactionrelationship',
            name='suggested_by',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
