# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_profileactionrelationship_suggested_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileactionrelationship',
            name='notes',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
    ]
