# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-10 17:51
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_profileactionrelationship_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileactionrelationship',
            name='privacy',
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=2500, null=True),
        ),
    ]
