# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-10 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_auto_20161210_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_privacy',
            field=models.CharField(choices=[(b'pub', 'Visible to Public'), (b'sit', 'Visible Sitewide'), (b'inh', 'Inherit')], default='sit', max_length=3),
        ),
    ]
