# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_auto_20161211_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacydefaults',
            name='global_default',
            field=models.CharField(choices=[(b'pub', 'Visible to Public'), (b'sit', 'Visible Sitewide'), (b'fol', 'Visible to Follows')], default='pub', max_length=3),
        ),
    ]
