# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 17:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0022_auto_20161214_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileactionrelationship',
            name='last_suggester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
