# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0023_profileactionrelationship_last_suggester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='current_privacy',
            field=models.CharField(choices=[(b'pub', 'Visible to Public'), (b'sit', 'Visible Sitewide'), (b'fol', 'Visible to Follows'), (b'inh', 'Inherit')], default='fol', max_length=3),
        ),
    ]
