# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 20:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0024_auto_20161219_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileactionrelationship',
            name='date_accepted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='profileactionrelationship',
            name='date_finished',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
