# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 04:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0025_auto_20161219_2048'),
        ('profiles', '0022_auto_20161214_0321'),
    ]

    operations = [
    ]
