# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-28 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0019_merge_20161220_0443'),
        ('profiles', '0026_merge_20161220_0443'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileSlateRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_of_additions', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
                ('slate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actions.Slate')),
            ],
        ),
    ]
