# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-28 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0019_merge_20161220_0443'),
        ('profiles', '0027_profileslaterelationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slates',
            field=models.ManyToManyField(through='profiles.ProfileSlateRelationship', to='actions.Slate'),
        ),
    ]
