# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-28 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0028_profile_slates'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='A_notifies_B',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relationship',
            name='B_notifies_A',
            field=models.BooleanField(default=False),
        ),
    ]
