# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-28 22:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0029_auto_20161228_2156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relationship',
            old_name='A_notifies_B',
            new_name='A_notified_of_B',
        ),
        migrations.RenameField(
            model_name='relationship',
            old_name='B_notifies_A',
            new_name='B_notified_of_A',
        ),
    ]
