# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-04 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0030_auto_20161228_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileactionrelationship',
            name='status',
            field=models.CharField(choices=[(b'sug', 'Suggested to you'), (b'ace', 'Accepted'), (b'don', 'Done'), (b'wit', 'Rejected'), (b'clo', 'Action was closed or withdrawn')], default='ace', max_length=3),
        ),
    ]
