# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-05 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0031_auto_20170104_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hide_location',
            field=models.BooleanField(default=False),
        ),
    ]
