# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-06 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0032_profile_hide_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='district',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
