# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0033_auto_20170106_0130'),
        ('actions', '0023_auto_20170111_1800'),
        ('slates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='slates',
            field=models.ManyToManyField(through='profiles.ProfileSlateRelationship', to='slates.Slate'),
        ),
        migrations.AlterField(
            model_name='profileslaterelationship',
            name='slate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slates.Slate'),
        ),
    ]
