# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-24 01:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0034_auto_20170111_1758'),
        ('location_plugin', '0004_auto_20170123_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='district',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='hide_location',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='lon',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='state',
        ),
    ]
