# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-08 23:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0035_auto_20170124_0142'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavbarSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_default', models.BooleanField(default=True)),
                ('links', models.CharField(blank=True, max_length=50, null=True)),
                ('use_default_landing', models.BooleanField(default=True)),
                ('landing_link', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='navbarsettings', to='profiles.Profile')),
            ],
        ),
    ]
