# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-29 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0035_auto_20170124_0142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='verified',
        ),
        migrations.AddField(
            model_name='profile',
            name='unverified',
            field=models.BooleanField(default=True),
        ),
    ]
