# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-09 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0037_auto_20170208_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbarsettings',
            name='landing_link',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
