# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-09 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0038_auto_20170209_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbarsettings',
            name='links',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
