# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-15 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0039_auto_20170209_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacydefaults',
            name='global_default',
            field=models.CharField(choices=[(b'public', 'Visible to Public'), (b'sitewide', 'Visible Sitewide'), (b'follows', 'Visible to Follows')], default=b'public', max_length=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='current_privacy',
            field=models.CharField(choices=[(b'public', 'Visible to Public'), (b'sitewide', 'Visible Sitewide'), (b'follows', 'Visible to Follows'), (b'inherit', 'Inherit')], default=b'follows', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='privacy',
            field=models.CharField(choices=[(b'public', 'Visible to Public'), (b'sitewide', 'Visible Sitewide'), (b'follows', 'Visible to Follows'), (b'inherit', 'Inherit')], default=b'inherit', max_length=10),
        ),
    ]
