# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-15 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0040_auto_20170315_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacydefaults',
            name='global_default',
            field=models.CharField(choices=[(b'public', 'Visible to Public'), (b'sitewide', 'Visible Sitewide'), (b'follows', 'Visible to Follows')], default=b'public', max_length=10),
        ),
    ]
