# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-15 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0041_auto_20170315_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileactionrelationship',
            name='status',
            field=models.CharField(choices=[(b'suggested', 'Suggested to you'), (b'accepted', 'Accepted'), (b'done', 'Done'), (b'rejected', 'Rejected'), (b'closed', 'Action was closed or withdrawn')], default=b'accepted', max_length=10),
        ),
    ]
