# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-15 18:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0043_auto_20170322_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navbarsettings',
            name='user',
        ),
        migrations.DeleteModel(
            name='NavbarSettings',
        ),
    ]
