# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-16 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0044_auto_20170415_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacydefaults',
            name='global_default',
            field=models.CharField(choices=[(b'public', 'Visible to public'), (b'sitewide', 'Visible sitewide'), (b'follows', 'Visible to follows')], default=b'public', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='current_privacy',
            field=models.CharField(choices=[(b'public', 'Visible to public'), (b'sitewide', 'Visible sitewide'), (b'follows', 'Visible to follows'), (b'inherit', 'Inherit')], default=b'follows', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='privacy',
            field=models.CharField(choices=[(b'public', 'Visible to public'), (b'sitewide', 'Visible sitewide'), (b'follows', 'Visible to follows'), (b'inherit', 'Inherit')], default=b'inherit', max_length=10),
        ),
    ]
