# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-03 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0045_auto_20170516_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='current_privacy',
            field=models.CharField(choices=[(b'public', 'Visible to public'), (b'sitewide', 'Visible sitewide'), (b'follows', 'Visible to follows'), (b'inherit', 'Inherit'), (b'members', 'Visible to group members')], default=b'follows', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='privacy',
            field=models.CharField(choices=[(b'public', 'Visible to public'), (b'sitewide', 'Visible sitewide'), (b'follows', 'Visible to follows'), (b'inherit', 'Inherit'), (b'members', 'Visible to group members')], default=b'inherit', max_length=10),
        ),
    ]
