# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 16:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('anonymize', models.BooleanField(default=False)),
                ('main_link', models.CharField(blank=True, max_length=300, null=True)),
                ('text', models.CharField(blank=True, max_length=500, null=True)),
                ('privacy', models.CharField(choices=[('pub', 'Visible to Public'), ('sit', 'Visible Sitewide'), ('fol', 'Visible to Buddies and Those You Follow'), ('bud', 'Visible to Buddies'), ('you', 'Only Visible to You'), ('inh', 'Inherit')], default='inh', max_length=3)),
                ('location', models.CharField(blank=True, max_length=140, null=True)),
                ('status', models.CharField(choices=[('cre', 'In creation'), ('rea', 'Ready for action'), ('wit', 'Withdrawn')], default='cre', max_length=3)),
                ('has_deadline', models.BooleanField(default=False)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActionTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('text', models.CharField(blank=True, max_length=200, null=True)),
                ('actions', models.ManyToManyField(blank=True, related_name='topics', to='actions.Action')),
            ],
        ),
        migrations.CreateModel(
            name='ActionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('text', models.CharField(blank=True, max_length=200, null=True)),
                ('actions', models.ManyToManyField(blank=True, related_name='actiontypes', to='actions.Action')),
            ],
        ),
    ]
