# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actiontopic',
            name='slug',
            field=models.CharField(default='zuzu-is-a-nice-cat', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actiontype',
            name='slug',
            field=models.CharField(default='woo-woo-woo', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
