# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 22:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('actions', '0002_auto_20161112_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('text', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('cre', 'In creation'), ('rea', 'Open for action'), ('fin', 'Finished'), ('wit', 'Withdrawn')], default='cre', max_length=3)),
                ('privacy', models.CharField(choices=[('pub', 'Visible to Public'), ('sit', 'Visible Sitewide'), ('fol', 'Visible to Buddies and Those You Follow'), ('bud', 'Visible to Buddies'), ('you', 'Only Visible to You'), ('inh', 'Inherit')], default='inh', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='SlateActionRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('med', 'Medium'), ('hig', 'High'), ('eme', 'Emergency')], default='med', max_length=3)),
                ('privacy', models.CharField(choices=[('pub', 'Visible to Public'), ('sit', 'Visible Sitewide'), ('fol', 'Visible to Buddies and Those You Follow'), ('bud', 'Visible to Buddies'), ('you', 'Only Visible to You'), ('inh', 'Inherit')], default='inh', max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='action',
            name='suggested_priority',
            field=models.CharField(choices=[('low', 'Low'), ('med', 'Medium'), ('hig', 'High'), ('eme', 'Emergency')], default='med', max_length=3),
        ),
        migrations.AlterField(
            model_name='action',
            name='status',
            field=models.CharField(choices=[('cre', 'In creation'), ('rea', 'Open for action'), ('fin', 'Finished'), ('wit', 'Withdrawn')], default='cre', max_length=3),
        ),
        migrations.AddField(
            model_name='slateactionrelationship',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actions.Action'),
        ),
        migrations.AddField(
            model_name='slateactionrelationship',
            name='slate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actions.Slate'),
        ),
        migrations.AddField(
            model_name='slate',
            name='actions',
            field=models.ManyToManyField(through='actions.SlateActionRelationship', to='actions.Action'),
        ),
        migrations.AddField(
            model_name='slate',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
