# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0003_auto_20161114_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actiontopic',
            name='actions',
        ),
        migrations.RemoveField(
            model_name='actiontype',
            name='actions',
        ),
        migrations.AddField(
            model_name='action',
            name='actiontypes',
            field=models.ManyToManyField(blank=True, related_name='actions_for_type', to='actions.ActionType'),
        ),
        migrations.AddField(
            model_name='action',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='actions_for_topic', to='actions.ActionTopic'),
        ),
    ]
