# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0004_auto_20161115_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='privacy',
            field=models.CharField(choices=[(b'pub', b'Visible to Public'), (b'sit', b'Visible Sitewide'), (b'inh', b'Inherit')], default='inh', max_length=3),
        ),
        migrations.AlterField(
            model_name='slate',
            name='privacy',
            field=models.CharField(choices=[(b'pub', b'Visible to Public'), (b'sit', b'Visible Sitewide'), (b'inh', b'Inherit')], default='inh', max_length=3),
        ),
        migrations.AlterField(
            model_name='slateactionrelationship',
            name='privacy',
            field=models.CharField(choices=[(b'pub', b'Visible to Public'), (b'sit', b'Visible Sitewide'), (b'inh', b'Inherit')], default='inh', max_length=3),
        ),
    ]
