# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 19:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0005_auto_20161116_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='slug',
            field=models.CharField(max_length=50, unique=True, validators=[[django.core.validators.RegexValidator(code='invalid', message='Please enter a valid slug, using only lowercase letters, numbers, and dashes.', regex=re.compile('^[a-z0-9-]+$'))]]),
        ),
        migrations.AlterField(
            model_name='slate',
            name='slug',
            field=models.CharField(max_length=50, unique=True, validators=[[django.core.validators.RegexValidator(code='invalid', message='Please enter a valid slug, using only lowercase letters, numbers, and dashes.', regex=re.compile('^[a-z0-9-]+$'))]]),
        ),
    ]
