# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 17:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0006_auto_20161118_1916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='suggested_priority',
            new_name='priority',
        ),
        migrations.AlterField(
            model_name='action',
            name='slug',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(code='invalid', message='Enter a slug, using only lowercase letters, numbers, and dashes.', regex=re.compile('^[a-z0-9-]+$'))]),
        ),
        migrations.AlterField(
            model_name='slate',
            name='slug',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(code='invalid', message='Enter a slug, using only lowercase letters, numbers, and dashes.', regex=re.compile('^[a-z0-9-]+$'))]),
        ),
    ]
