# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0007_auto_20161120_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='status',
            field=models.CharField(choices=[(b'rea', b'Open for action'), (b'fin', b'Finished'), (b'wit', b'Withdrawn')], default='cre', max_length=3),
        ),
        migrations.AlterField(
            model_name='slate',
            name='status',
            field=models.CharField(choices=[(b'rea', b'Open for action'), (b'fin', b'Finished'), (b'wit', b'Withdrawn')], default='cre', max_length=3),
        ),
    ]
