# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0009_auto_20161120_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='slateactionrelationship',
            name='status',
            field=models.CharField(choices=[(b'sug', b'Suggested to you'), (b'ace', b'Accepted'), (b'don', b'Done'), (b'wit', b'Rejected')], default='ace', max_length=3),
        ),
    ]
