# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 02:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0010_slateactionrelationship_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='text',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='actiontopic',
            old_name='text',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='actiontype',
            old_name='text',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='slate',
            old_name='text',
            new_name='description',
        ),
    ]
