# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 04:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0011_auto_20161122_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='slate',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
