# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0012_auto_20161122_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='description',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='slate',
            name='description',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
    ]
