# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0016_auto_20161210_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='current_privacy',
            field=models.CharField(choices=[(b'pub', 'Visible to Public'), (b'sit', 'Visible Sitewide'), (b'fol', 'Visible to Follows'), (b'inh', 'Inherit')], default='sit', max_length=3),
        ),
        migrations.AlterField(
            model_name='action',
            name='privacy',
            field=models.CharField(choices=[(b'pub', 'Visible to Public'), (b'sit', 'Visible Sitewide'), (b'fol', 'Visible to Follows'), (b'inh', 'Inherit')], default='inh', max_length=3),
        ),
        migrations.AlterField(
            model_name='slate',
            name='current_privacy',
            field=models.CharField(choices=[(b'pub', 'Visible to Public'), (b'sit', 'Visible Sitewide'), (b'fol', 'Visible to Follows'), (b'inh', 'Inherit')], default='sit', max_length=3),
        ),
        migrations.AlterField(
            model_name='slate',
            name='privacy',
            field=models.CharField(choices=[(b'pub', 'Visible to Public'), (b'sit', 'Visible Sitewide'), (b'fol', 'Visible to Follows'), (b'inh', 'Inherit')], default='inh', max_length=3),
        ),
    ]
