# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 02:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0015_auto_20161201_0332'),
        ('actions', '0017_auto_20161211_2155'),
    ]

    operations = [
    ]
