# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0017_auto_20161211_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='duration',
            field=models.CharField(choices=[(b'A', 'Ten minutes or less'), (b'B', 'Under an hour'), (b'C', 'A few hours'), (b'E', 'A day or more, not ongoing'), (b'F', 'Minor ongoing commitment'), (b'G', 'Major ongoing commitment'), (b'H', 'Unknown or variable')], default='H', max_length=2),
        ),
    ]
