# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 04:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0018_action_duration'),
        ('actions', '0018_merge_20161214_0228'),
    ]

    operations = [
    ]
