# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-06 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0033_auto_20170106_0130'),
        ('actions', '0020_auto_20170104_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='district',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='District',
        ),
    ]
