# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 18:00
from __future__ import unicode_literals

from django.db import migrations

# Custom migration created as part of the process of moving slates & sars to their
# own app

class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0021_auto_20170106_0130'),
    ]

    # Add custom database_operations
    database_operations = [
        migrations.AlterModelTable('slate', 'slates_slate'),
        migrations.AlterModelTable('slateactionrelationship', 'slates_slateactionrelationship'),
    ]

    # Don't modify the Django 'state' yet
    state_operations = [

    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]
