# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 18:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0023_auto_20170111_1800'),
        ('slates', '0001_initial'),
        ('profiles', '0034_auto_20170111_1758'),
    ]

    # This needs to be a state-only operation because the database model was
    # renamed, and no longer exists according to Django.
    state_operations = [
        # Pasted from auto-generated operations in previous step:
        migrations.DeleteModel(
            name='Slate',
        ),
        migrations.DeleteModel(
            name='SlateActionRelationship',
        ),
    ]

    operations = [
        # After this state operation, the Django DB state should match the
        # actual database structure.
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
