# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-31 20:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('actions', '0026_auto_20170124_0142'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('kinds', models.CharField(blank=True, max_length=300, null=True)),
                ('topics', models.CharField(blank=True, max_length=300, null=True)),
                ('time', models.CharField(blank=True, max_length=300, null=True)),
                ('friends', models.BooleanField(default=False)),
                ('plugin_fields', models.CharField(blank=True, max_length=500, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
