# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-09 14:33
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0027_actionfilter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=4000, null=True),
        ),
    ]
