# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-07 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0028_auto_20170209_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='keep_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='action',
            name='keep_open_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
