# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-15 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0029_auto_20170307_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='current_privacy',
            field=models.CharField(choices=[(b'public', 'Visible to Public'), (b'sitewide', 'Visible Sitewide'), (b'follows', 'Visible to Follows'), (b'inherit', 'Inherit')], default=b'sitewide', max_length=10),
        ),
        migrations.AlterField(
            model_name='action',
            name='privacy',
            field=models.CharField(choices=[(b'public', 'Visible to Public'), (b'sitewide', 'Visible Sitewide'), (b'follows', 'Visible to Follows'), (b'inherit', 'Inherit')], default=b'inherit', max_length=10),
        ),
    ]
