# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-15 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0030_auto_20170315_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='status',
            field=models.CharField(choices=[(b'ready', 'Open for action'), (b'finished', 'Finished'), (b'withdrawn', 'Withdrawn')], default=b'ready', max_length=10),
        ),
    ]
