# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-20 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0033_auto_20170322_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='special_action',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
