# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-16 18:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0035_auto_20170516_1846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='has_deadline',
            new_name='never_expires',
        ),
    ]
