# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-17 21:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0036_auto_20170516_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='keep_open_date',
            new_name='close_date',
        ),
        migrations.RemoveField(
            model_name='action',
            name='keep_open',
        ),
    ]
