# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-07 22:12
from __future__ import unicode_literals

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(code=b'invalid', message=b'Enter a slug, using only lowercase letters, numbers, and dashes.', regex=re.compile(b'^[a-z0-9-]+$'))])),
                ('title', models.CharField(max_length=300)),
                ('description', ckeditor.fields.RichTextField(blank=True, max_length=5000, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
