# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-07 22:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(blank=True, max_length=50, unique=True, validators=[django.core.validators.RegexValidator(code=b'invalid', message=b'Enter a slug, using only lowercase letters, numbers, and dashes.', regex=re.compile(b'^[a-z0-9-]+$'))]),
        ),
    ]
