# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-07 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170207_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
