# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0034_auto_20170111_1758'),
        ('actions', '0024_auto_20170111_1807'),
        ('slates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('kind', models.CharField(choices=[('topic', 'Topic'), ('type', 'Type'), ('goal', 'Goal')], default='topic', max_length=10)),
                ('actions', models.ManyToManyField(blank=True, related_name='action_tags', to='actions.Action')),
                ('profiles', models.ManyToManyField(blank=True, related_name='profile_tags', to='profiles.Profile')),
                ('slates', models.ManyToManyField(blank=True, related_name='slate_tags', to='slates.Slate')),
            ],
        ),
    ]
