# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 20:47
from __future__ import unicode_literals

from django.db import migrations

def convert_old_tags_to_new(apps, schema_editor):
    # Get the Tag model at the time of migration
    Tag = apps.get_model("tags", "Tag")
    # Get the ActionTopic at the time of migration and add them all.
    ActionTopic = apps.get_model("actions", "ActionTopic")
    for a in ActionTopic.objects.all():
        tag = Tag.objects.create(name=a.name, slug=a.slug, description=a.description, kind="topic")
        for action in a.actions_for_topic.all():
            tag.actions.add(action)
    # Get the ActionType at the time of migration and add them all.
    ActionType = apps.get_model("actions", "ActionType")
    for a in ActionType.objects.all():
        tag = Tag.objects.create(name=a.name, slug=a.slug, description=a.description, kind="type")
        for action in a.actions_for_type.all():
            tag.actions.add(action)

class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(convert_old_tags_to_new),
    ]
