# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_auto_20170111_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='actions',
            field=models.ManyToManyField(blank=True, related_name='tags', to='actions.Action'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='profiles',
            field=models.ManyToManyField(blank=True, related_name='tags', to='profiles.Profile'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slates',
            field=models.ManyToManyField(blank=True, related_name='tags', to='slates.Slate'),
        ),
    ]
