# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-08 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20170608_0225'),
        ('tags', '0003_auto_20170112_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='tags', to='groups.GroupProfile'),
        ),
    ]
