# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 23:43
from __future__ import unicode_literals

from django.db import migrations

def move_locations_to_new_model(apps, schema_editor):
    # Get location model at time of migration
    Location = apps.get_model("location_plugin", "Location")
    # Get content types model at time of migration
    ContentType = apps.get_model('contenttypes', 'ContentType')
    # Get profile model and move profile location data
    Profile = apps.get_model("profiles", "Profile")
    p_type = ContentType.objects.get_for_model(Profile)
    for p in Profile.objects.all():
        loc = Location.objects.create(location=p.location, lat=p.lat, lon=p.lon,
            district=p.district, state=p.state, content_type=p_type, object_id=p.pk)
    # Get action model and move action location data
    Action = apps.get_model("actions", "Action")
    a_type = ContentType.objects.get_for_model(Action)
    for a in Action.objects.all():
        loc = Location.objects.create(location=a.location, lat=a.lat, lon=a.lon,
            district=a.district, state=a.state, content_type=a_type, object_id=a.pk)

class Migration(migrations.Migration):

    dependencies = [
        ('location_plugin', '0001_initial'),
        ('profiles', '0034_auto_20170111_1758'),
        ('actions', '0025_auto_20170112_0128'),
    ]

    operations = [
        migrations.RunPython(move_locations_to_new_model),
    ]
