# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-13 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_plugin', '0002_auto_20170112_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='hide_location',
            field=models.BooleanField(default=False),
        ),
    ]
