# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-23 18:15
from __future__ import unicode_literals

from django.db import migrations

def generate_empty_slate_locations(apps, schema_editor):
    # Get location model at time of migration
    Location = apps.get_model("location_plugin", "Location")
    # Get content types model at time of migration
    ContentType = apps.get_model('contenttypes', 'ContentType')
    # Get slate model and create empty slate locations
    Slate = apps.get_model("slates", "Slate")
    s_type = ContentType.objects.get_for_model(Slate)
    for s in Slate.objects.all():
        loc = Location.objects.create(content_type=s_type, object_id=s.pk)

class Migration(migrations.Migration):

    dependencies = [
        ('location_plugin', '0003_location_hide_location'),
    ]

    operations = [
        migrations.RunPython(generate_empty_slate_locations),
    ]
