# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-08 01:53
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privacy', models.CharField(choices=[(b'public', 'Visible to public'), (b'sitewide', 'Visible sitewide'), (b'members', b'Visible to group members')], default=b'public', max_length=10)),
                ('description', ckeditor.fields.RichTextField(blank=True, max_length=4000, null=True)),
                ('summary', models.CharField(blank=True, max_length=300, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('admin_group', 'Administer group'),),
            },
        ),
    ]
