# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-08 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20170608_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupprofile',
            name='groupname',
            field=models.CharField(default='defaultgroupname', max_length=140),
            preserve_default=False,
        ),
    ]
