# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-03 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_groupprofile_groupname'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupprofile',
            name='membership',
            field=models.CharField(choices=[(b'open', 'Members can join without approval'), (b'request', 'Members must request to join and be approved'), (b'invite', 'Members must be invited')], default=b'open', max_length=7),
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='privacy',
            field=models.CharField(choices=[(b'public', 'Visible to public'), (b'sitewide', 'Visible sitewide'), (b'follows', 'Visible to follows'), (b'members', 'Visible to group members')], default=b'public', max_length=10),
        ),
    ]
