# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-07 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_pendingmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingmember',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.GroupProfile'),
        ),
    ]
