# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 19:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0030_auto_20161228_2210'),
        ('actions', '0019_merge_20161220_0443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commitment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(b'waiting', 'Commitment made, not yet at deadline'), (b'active', 'Commitment made, past deadline'), (b'closed', 'Commitment carried out'), (b'removed', 'User deleted par')], default='waiting', max_length=10)),
                ('buddies', models.CharField(blank=True, max_length=400, null=True)),
                ('message', models.CharField(blank=True, max_length=400, null=True)),
                ('start_emails', models.DateTimeField(default=django.utils.timezone.now)),
                ('tries', models.IntegerField(default=3)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actions.Action')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
            ],
        ),
    ]
