# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commitments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commitment',
            name='buddies',
            field=models.CharField(default='shaunagm@gmail.com', max_length=400),
            preserve_default=False,
        ),
    ]
