# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commitments', '0002_auto_20170103_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitment',
            name='offsite_buddies',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='commitment',
            name='buddies',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
