# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-04 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('commitments', '0003_auto_20170103_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commitment',
            name='start_emails',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='commitment',
            name='status',
            field=models.CharField(choices=[(b'waiting', 'Commitment made, not yet at deadline'), (b'active', 'Commitment made, past deadline'), (b'completed', 'Commitment carried out'), (b'expired', 'Commitment expired, user took too long'), (b'removed', 'Par was closed or deleted')], default='waiting', max_length=10),
        ),
    ]
