# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-04 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('commitments', '0004_auto_20170104_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commitment',
            name='start_emails',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
