# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-07 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commitments', '0005_auto_20170104_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitment',
            name='days_before_emailing',
            field=models.IntegerField(default=14),
        ),
    ]
