# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 17:56
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('reasoning', ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True)),
                ('self_submitted', models.BooleanField(default=False)),
                ('self_request_status', models.CharField(choices=[('submitted', 'Requested submitted'), ('approved', 'Request approved by admin'), ('emailed', 'Approval email sent'), ('done', 'User has joined site')], default='submitted', max_length=10)),
                ('invited_status', models.CharField(choices=[('submitted', 'Invite request submitted'), ('approved', 'Invite request approved by admin'), ('emailed', 'Invite confirmation email sent'), ('done', 'User has joined site')], default='submitted', max_length=10)),
                ('invited_by', models.CharField(blank=True, max_length=500, null=True)),
                ('initial_request_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
