# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
