# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0002_auto_20161214_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='confirmation_url_string',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
