# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0003_invite_confirmation_url_string'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='invited_status',
        ),
        migrations.RemoveField(
            model_name='invite',
            name='self_request_status',
        ),
        migrations.AddField(
            model_name='invite',
            name='request_status',
            field=models.CharField(choices=[('submitted', 'Request submitted'), ('approved', 'Request approved by admin'), ('emailed', 'Confirmation email sent'), ('done', 'User has joined site')], default='submitted', max_length=10),
        ),
    ]
