# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0005_auto_20161214_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='requester_hash',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='invite',
            name='request_status',
            field=models.CharField(choices=[('submitted', 'Request submitted'), ('approved', 'Request approved by admin'), ('emailed', 'Confirmation email sent'), ('done', 'User has joined site'), ('duplicate', 'User already on site')], default='submitted', max_length=10),
        ),
    ]
