# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0006_auto_20161214_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='message',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='invite',
            name='reasoning',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
