# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-31 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import invites.models


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0009_auto_20170129_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='email',
            field=models.CharField(max_length=50, unique=True, validators=[invites.models.validate_email]),
        ),
        migrations.AlterField(
            model_name='invite',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[invites.models.validate_username]),
        ),
    ]
