# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsettings',
            name='if_actions_followed',
            field=models.BooleanField(default=True),
        ),
    ]
