# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 23:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationsettings_if_actions_followed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationsettings',
            name='event_driven',
        ),
    ]
