# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_remove_notificationsettings_event_driven'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsettings',
            name='if_suggested_action',
            field=models.BooleanField(default=True),
        ),
    ]
