# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-28 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notificationsettings_if_suggested_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsettings',
            name='if_slate_followed',
            field=models.BooleanField(default=True),
        ),
    ]
