# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-28 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_notificationsettings_if_slate_followed'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsettings',
            name='if_followed_slates_updated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='if_followed_users_create',
            field=models.BooleanField(default=True),
        ),
    ]
