# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-29 01:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0006_auto_20161228_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyActionSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recently_seen', models.CharField(blank=True, max_length=50, null=True)),
                ('my_own_actions', models.CharField(choices=[(b'many', 'A lot'), (b'few', 'A little'), (b'none', 'None')], default='few', max_length=5)),
                ('my_friends_actions', models.CharField(choices=[(b'many', 'A lot'), (b'few', 'A little'), (b'none', 'None')], default='few', max_length=5)),
                ('popular_actions', models.CharField(choices=[(b'many', 'A lot'), (b'few', 'A little'), (b'none', 'None')], default='few', max_length=5)),
                ('duration_filter', models.CharField(blank=True, max_length=200, null=True)),
                ('action_type_filter', models.CharField(blank=True, max_length=200, null=True)),
                ('action_topic_filter', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
