# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-29 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_dailyactionsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyactionsettings',
            name='action_topic_filter_on',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyactionsettings',
            name='action_type_filter_on',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyactionsettings',
            name='duration_filter_on',
            field=models.BooleanField(default=False),
        ),
    ]
