# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 01:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_auto_20161229_0149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyactionsettings',
            old_name='action_topic_filter',
            new_name='tag_filter',
        ),
        migrations.RenameField(
            model_name='dailyactionsettings',
            old_name='action_topic_filter_on',
            new_name='tag_filter_on',
        ),
        migrations.RemoveField(
            model_name='dailyactionsettings',
            name='action_type_filter',
        ),
        migrations.RemoveField(
            model_name='dailyactionsettings',
            name='action_type_filter_on',
        ),
    ]
