# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-07 23:07
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_auto_20170112_0128'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('preheader_text', models.CharField(blank=True, max_length=300, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('body', ckeditor.fields.RichTextField(blank=True, max_length=5000, null=True)),
                ('read_more_link', models.CharField(max_length=200)),
                ('read_more_text', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('test', 'Test Email'), ('send', 'Send to Users'), ('done', 'Done')], default='draft', max_length=5)),
            ],
        ),
    ]
