# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-05 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_genericemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericemail',
            name='plain_body',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
