# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-05 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0011_genericemail_plain_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericemail',
            name='read_more_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='genericemail',
            name='read_more_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
