# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 17:58
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import re

# Migration is part of the process of moving slates & sars to their own app

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('actions', '0023_auto_20170111_1800'), # Depend on custom action migration
    ]

    state_operations = [
        migrations.CreateModel(
            name='Slate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(code=b'invalid', message=b'Enter a slug, using only lowercase letters, numbers, and dashes.', regex=re.compile(b'^[a-z0-9-]+$'))])),
                ('title', models.CharField(max_length=300)),
                ('description', ckeditor.fields.RichTextField(blank=True, max_length=2500, null=True)),
                ('status', models.CharField(choices=[(b'rea', 'Open for action'), (b'fin', 'Finished'), (b'wit', 'Withdrawn')], default='rea', max_length=3)),
                ('privacy', models.CharField(choices=[(b'pub', 'Visible to Public'), (b'sit', 'Visible Sitewide'), (b'fol', 'Visible to Follows'), (b'inh', 'Inherit')], default='inh', max_length=3)),
                ('current_privacy', models.CharField(choices=[(b'pub', 'Visible to Public'), (b'sit', 'Visible Sitewide'), (b'fol', 'Visible to Follows'), (b'inh', 'Inherit')], default='sit', max_length=3)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SlateActionRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[(b'low', 'Low'), (b'med', 'Medium'), (b'hig', 'High'), (b'eme', 'Emergency')], default='med', max_length=3)),
                ('status', models.CharField(choices=[(b'sug', 'Suggested to you'), (b'ace', 'Accepted'), (b'don', 'Done'), (b'wit', 'Rejected'), (b'clo', 'Action was closed or withdrawn')], default='ace', max_length=3)),
                ('notes', models.CharField(blank=True, max_length=2500, null=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actions.Action')),
                ('slate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slates.Slate')),
            ],
        ),
        migrations.AddField(
            model_name='slate',
            name='actions',
            field=models.ManyToManyField(through='slates.SlateActionRelationship', to='actions.Action'),
        ),
        migrations.AddField(
            model_name='slate',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]

    operations = [
        # By running only state operations, we are making Django think it has
        # applied this migration to the database. In reality, we renamed a
        # "cars_tires" table to "tires_tires" earlier.
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]    
