# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-15 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slates', '0002_auto_20170315_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slate',
            name='status',
            field=models.CharField(choices=[(b'ready', 'Open for action'), (b'finished', 'Finished'), (b'withdrawn', 'Withdrawn')], default=b'ready', max_length=10),
        ),
        migrations.AlterField(
            model_name='slateactionrelationship',
            name='status',
            field=models.CharField(choices=[(b'suggested', 'Suggested to you'), (b'accepted', 'Accepted'), (b'done', 'Done'), (b'rejected', 'Rejected'), (b'closed', 'Action was closed or withdrawn')], default=b'accepted', max_length=10),
        ),
    ]
