# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-22 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slates', '0003_auto_20170315_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slateactionrelationship',
            name='priority',
            field=models.CharField(choices=[(b'low', 'Low'), (b'medium', 'Medium'), (b'high', 'High'), (b'emergency', 'Emergency')], default=b'medium', max_length=10),
        ),
    ]
