# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-16 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slates', '0004_auto_20170322_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slate',
            name='current_privacy',
            field=models.CharField(choices=[(b'public', 'Visible to public'), (b'sitewide', 'Visible sitewide'), (b'follows', 'Visible to follows'), (b'inherit', 'Inherit')], default=b'sitewide', max_length=10),
        ),
        migrations.AlterField(
            model_name='slate',
            name='privacy',
            field=models.CharField(choices=[(b'public', 'Visible to public'), (b'sitewide', 'Visible sitewide'), (b'follows', 'Visible to follows'), (b'inherit', 'Inherit')], default=b'inherit', max_length=10),
        ),
    ]
