# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-31 18:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slates', '0006_auto_20170803_2249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slate',
            options={'permissions': (('administer_slate', 'Administer slate'), ('contribute_actions', 'Contribute actions to slate'))},
        ),
    ]
