# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-31 19:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slates', '0007_auto_20170831_1811'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slate',
            options={'permissions': (('administer_slate', 'Administer slate'), ('contribute_actions', 'Contribute actions to slate'), ('view_slate', 'View slate'))},
        ),
    ]
